<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Импортируем-библиотеки" data-toc-modified-id="Импортируем-библиотеки-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Импортируем библиотеки</a></span></li><li><span><a href="#Откроем-и-изучим-файлы" data-toc-modified-id="Откроем-и-изучим-файлы-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Откроем и изучим файлы</a></span><ul class="toc-item"><li><span><a href="#Посмотрим-наименования-полей-и-типы-данных" data-toc-modified-id="Посмотрим-наименования-полей-и-типы-данных-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Посмотрим наименования полей и типы данных</a></span></li></ul></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Модель-линейной-регрессии" data-toc-modified-id="Модель-линейной-регрессии-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Модель линейной регрессии</a></span></li><li><span><a href="#Исследуем-качество-модели-до-преобразования" data-toc-modified-id="Исследуем-качество-модели-до-преобразования-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Исследуем качество модели до преобразования</a></span></li><li><span><a href="#Преобразуем-данные" data-toc-modified-id="Преобразуем-данные-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Преобразуем данные</a></span></li><li><span><a href="#Разобьем-зашифрованные-данные-на-выборки" data-toc-modified-id="Разобьем-зашифрованные-данные-на-выборки-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Разобьем зашифрованные данные на выборки</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Необходимо защитить данные клиентов страховой компании «Хоть потоп». Разработать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию, обосновать корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

### Импортируем библиотеки

In [1]:
import pandas as pd
import numpy.matlib
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

### Откроем и изучим файлы

In [2]:
data = pd.read_csv('insurance.csv')

#### Посмотрим наименования полей и типы данных

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [5]:
data.tail()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

In [6]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

<b> Проверим столбцы на пропуски </b>

In [7]:
pd.DataFrame(round(data.isna().mean()*100,)).style.background_gradient('coolwarm')

Пропуски отсутствуют  

In [8]:
data['Пол'].unique()

array([1, 0], dtype=int64)

In [9]:
data['Возраст'].unique()

array([41., 46., 29., 21., 28., 43., 39., 25., 36., 32., 38., 23., 40.,
       34., 26., 42., 27., 33., 47., 30., 19., 31., 22., 20., 24., 18.,
       37., 48., 45., 44., 52., 49., 35., 56., 65., 55., 57., 54., 50.,
       53., 51., 58., 59., 60., 61., 62.])

In [10]:
data['Члены семьи'].unique()

array([1, 0, 2, 4, 3, 5, 6], dtype=int64)

In [11]:
data['Страховые выплаты'].unique()

array([0, 1, 2, 3, 5, 4], dtype=int64)

<b> Вывод:</b>
Выполнена загрузка и обзор данных, пропусков и аномалий не обнаружено

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** При умножении признаков на обратимую матрицу качество линейной регрессии не изменится.

**Обоснование:**
Подставим формулу вектора весов $w$ в формулу предсказаний $a = Xw$:

$$
a = Xw = X(X^T X)^{-1} X^T y
$$

Умножим матрицу признаков $X$ на обратимую матрицу $P$
                                 
$$
XP((XP)^T XP)^{-1}(XP)^T y =
$$
                                
$$
= XP(P^T X^T X P)^{-1} (XP)^T y =
$$

$$
= XP((P^T)(X^T X)(P))^{-1} (XP)^T y =
$$

$$
= XP P^{-1} (X^T X)^{-1} (P^T)^{-1} (XP)^T y =
$$



$$
= XP P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y =
$$


Произведение $ (P^T)^{-1} P^T$  и $ P P^{-1} $ являются единичными матрицами $E$

$$
= X (X^T X)^{-1} X^T y = Xw = a
$$

## Алгоритм преобразования

**Алгоритм**

Для защиты информации выполним следующие действия:
1. Разделим данные по целевому признаку на 2 выборки: features и target;
2. Построим модель линейной регресии;
3. Исследуем качество модели;
4. Матрицу признаков умножим на обратимую матрицу, которая будет генерироваться случайным образом;
5. Построим вторую модель линейной регрессии с преобразованными данными;
6. Исследуем качество второй модели;
7. Сравним метрики первой и второй моделей.

**Обоснование**

Генерируемая матрица P должна иметь размерность (nxn) и быть невырожденной, где n - количество признаков модели линейной регресси. Матрица является невырожденной, если ее опредилитель не равен 0, а умножение матрицы P на обратную дает единичную матрицу. Также число строк матрицы P равно числу столбцов матрице признаков X, здесь X еще без нулевого столбца, он добавляется в внутри модели линейной регрессии. Таким образом новая матрица будет иметь ту же размерность, что и матрица X.

Так как у линейной регрессии признаки — это вектор чисел в n-мерном пространстве (допустим, x). Предсказание модели (a) вычисляется так: скалярно умножается вектор признаков на вектор весов w, затем к этому произведению прибавляется величина сдвига предсказания w0: a=(x,w)+w0, вектор w и скаляр w0 — это параметры модели. В векторе w параметров n, а в w0 — один. То есть количество параметров больше длины вектора признаков на единицу. Поэтому к матрице признаков X дополнительно присоединяют вектор-столбец из единиц — X=[1∣X] и ее размерность увеличивается на 1.

## Проверка алгоритма

### Модель линейной регрессии 

In [12]:
class LinearRegression:
    def fit(self, train_features, train_target): 
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0
    
    def R2(self, test_features, test_target):
        test_predict = self.predict(test_features)
        mse_model = np.sum((test_target - test_predict)**2)
        mse_data = np.sum((test_target - np.mean(test_target))**2)
        return 1 - mse_model/mse_data

<b> Подготовка признаков </b>

In [13]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

### Исследуем качество модели до преобразования

Разделим данные на обучающие и тестовые выборки 

In [14]:
features_train, features_valid, target_train, target_valid = train_test_split(features, target, test_size=0.25, random_state=12345)

<b> Обучим модель LinearRegression и посмотрим на показатели метрики R2 на выборках. </b>

In [15]:
model = LinearRegression()
model.fit(features_train, target_train)
print('Метрика R2 линейной регрессии (train): ', model.R2(features_train, target_train))
print('Метрика R2 линейной регрессии (valid): ', model.R2(features_valid, target_valid))

Метрика R2 линейной регрессии (train):  0.4213920242579371
Метрика R2 линейной регрессии (valid):  0.43522757127026657


### Преобразуем данные

In [16]:
np.random.seed(12345)
def get_trans(features):
    n = features.shape[1]
    while True:
        P = np.matlib.rand((n,n)) 
        P_det = np.linalg.det(P)
        print(f'Оперделитель матрицы: {P_det}')
        check_prop = np.prod(np.round(P.dot(np.linalg.inv(P))) == np.eye(n)) 
        if P_det and check_prop:
            break
    return features.dot(P), P

In [17]:
features_cipher, P = get_trans(features)

Оперделитель матрицы: -0.05543310984078479


In [18]:
pd.DataFrame(features_cipher.values, columns= data.columns[:-1]).head(5)

Пол       Возраст      Зарплата   Члены семьи
0  37169.983952  32441.905747  37126.682258  47708.455342
1  28484.575966  24863.156593  28457.829124  36560.358528
2  15743.503414  13742.238084  15729.981916  20206.383593
3  31241.345787  27266.582942  31200.559759  40101.520436
4  19563.289157  17075.165256  19542.546847  25108.599330

### Разобьем зашифрованные данные на выборки

In [19]:
features_train, features_valid, target_train, target_valid = train_test_split(features_cipher, target, test_size=0.25, random_state=12345)

<b> Обучим модель LinearRegression и посмотрим на показатели метрики R2 на выборках. </b>

In [20]:
model = LinearRegression()
model.fit(features_train, target_train)
print('Метрика R2 линейной регрессии (train): ', model.R2(features_train, target_train))
print('Метрика R2 линейной регрессии (valid): ', model.R2(features_valid, target_valid))

Метрика R2 линейной регрессии (train):  0.4213920242573158
Метрика R2 линейной регрессии (valid):  0.4352276372038495


<b> Вывод: </b>

Данные были загружены и изучены. Исследован вопрос о влиянии умножения матрицы признаков на обратимую матрицу. Качество линейной регрессии не изменится. Сформирован и реализован алгоритм преобразования данных на основе проведенного исследования. Сформированный алгоритм был запрограммирован, реализован класс модели LinearRegression и проведено тестирование моделей по двум направлениям:
* Исследовано качество модели без шифрования;
* Исследовано качество модели с шифрованием.

Показатели метрики R2 на модели до преобразования данных и после преобразорвания данных одинаковы.